#!/bin/bash

echo "🔧 AWS Configuration Helper"
echo "============================"
echo ""
echo "This script will help you configure AWS credentials."
echo ""
echo "You need:"
echo "  1. AWS Access Key ID"
echo "  2. AWS Secret Access Key"
echo ""
echo "To get these:"
echo "  1. Go to: https://console.aws.amazon.com"
echo "  2. Navigate to: IAM → Users → Your User → Security Credentials"
echo "  3. Click 'Create access key'"
echo "  4. Choose 'Command Line Interface (CLI)'"
echo "  5. Copy both keys"
echo ""
read -p "Press Enter when you have your keys ready..."

echo ""
echo "Now run: aws configure"
echo ""
echo "You'll be prompted for:"
echo "  - AWS Access Key ID: [paste your access key]"
echo "  - AWS Secret Access Key: [paste your secret key]"
echo "  - Default region: ca-central-1 (or your preferred region)"
echo "  - Default output format: json (just press Enter)"
echo ""

